###
GET http://localhost:3000


### Fetch All Songs
GET http://localhost:3000/songs


### Fetch Single Song
GET http://localhost:3000/songs/3


### Create New Song
POST http://localhost:3000/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcxMjAxNzIzMSwiZXhwIjoxNzEyNjIyMDMxfQ.zG4rI3DkMTwmV5xi_fCKKfwYr58S_-iEyW61beBMBH8
Content-Type: application/json

{
  "title": "Four Five Seconds",
  "artists": ["Rihanna", "Kanye West", "Paul McCartney"],
  "releasedDate": "2015-01-24",
  "duration": "03:08"
}

### Update Song
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
  "title": "Calm Down",
  "artists": ["Rihanna"],
  "releasedDate": "2015-06-30",
  "duration": "04:08"
}


### Delete single Song
DELETE http://localhost:3000/songs/4


### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "janedoe@gmail.com",
  "password": "1234567890"
}


### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "1234567890"
}

### Get Profile
GET http://localhost:3000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcxMjAxNzIzMSwiZXhwIjoxNzEyNjIyMDMxfQ.zG4rI3DkMTwmV5xi_fCKKfwYr58S_-iEyW61beBMBH8


### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcxMjAxNzIzMSwiZXhwIjoxNzEyNjIyMDMxfQ.zG4rI3DkMTwmV5xi_fCKKfwYr58S_-iEyW61beBMBH8


### Validate 2FA
POST http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcxMjAxNzIzMSwiZXhwIjoxNzEyNjIyMDMxfQ.zG4rI3DkMTwmV5xi_fCKKfwYr58S_-iEyW61beBMBH8
Content-Type: application/json

{
  "token": "628390"
}